[heltec_htcc_ab01]
extends = cubecell_base
board = heltec_htcc_ab01
build_flags = ${cubecell_base.build_flags}
  -I variants/heltec_htcc_ab01
  -D HELTEC_HTCC_AB01
  -D USE_SX1262
  -D RADIOLIB_EXCLUDE_LORAWAN=1
  -D RADIOLIB_EXCLUDE_LR2021=1
  -D RADIOLIB_EXCLUDE_LR11X0=1
  -D RADIOLIB_EXCLUDE_SX127X=1
  -D RADIOLIB_EXCLUDE_SX126X=0
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D P_LORA_DIO_1=P4_6
  -D P_LORA_NSS=P4_3
  -D P_LORA_RESET=P5_7
  -D P_LORA_BUSY=P4_7
  -D P_LORA_SCLK=P4_2
  -D P_LORA_MISO=P4_1
  -D P_LORA_MOSI=P4_0
  -D PIN_USER_BTN=P3_3
  -D PIN_VEXT_EN=P3_2
  -D PIN_VEXT_EN_ACTIVE=LOW
  -D LORA_TX_POWER=10 ;If it is configured as 10 here, the final output will be 22 dbm.
  -D MAX_LORA_TX_POWER=22 ; Max SX1262 output
  -D SX126X_REGISTER_PATCH=1       ; Patch register 0x8B5 for improved RX
  -D SX126X_DIO2_AS_RF_SWITCH=true ; GC1109 CTX is controlled by SX1262 DIO2
  -D SX126X_DIO3_TCXO_VOLTAGE=1.8
  -D SX126X_CURRENT_LIMIT=140
  -D SX126X_RX_BOOSTED_GAIN=1      ; In some cases, commenting this out will improve RX
  -D ENV_INCLUDE_GPS=0
  -D PIN_ADC_CTRL=P3_3
  -D PIN_VBAT_READ=P2_3
  -D PIN_ANT_ENABLE=P6_1
build_src_filter = ${cubecell_base.build_src_filter}
  +<../variants/heltec_htcc_ab01>

[env:heltec_htcc_ab01_repeater]
extends = heltec_htcc_ab01
build_flags = ${heltec_htcc_ab01.build_flags}
  -D ADVERT_NAME='"heltec_htcc_ab01 Repeater"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=5
build_src_filter = ${heltec_htcc_ab01.build_src_filter}
  +<../examples/simple_repeater>

[env:heltec_htcc_ab01_sensor]
extends = heltec_htcc_ab01
build_flags = ${heltec_htcc_ab01.build_flags}
  -D ADVERT_NAME='"heltec_htcc_ab01 Sensor"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=5
build_src_filter = ${heltec_htcc_ab01.build_src_filter}
  +<../examples/simple_sensor>

[env:heltec_htcc_ab01_companion_radio_usb]
extends = heltec_htcc_ab01
build_flags = ${heltec_htcc_ab01.build_flags}
  -D FORMAT_FS=true
  -D MAX_CONTACTS=2
  -D MAX_GROUP_CHANNELS=1
  -D MAX_LORA_TX_POWER=22
build_src_filter = ${heltec_htcc_ab01.build_src_filter}
  +<../examples/companion_radio/*.cpp>
lib_deps = ${heltec_htcc_ab01.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:heltec_htcc_ab01_kiss_modem]
extends = heltec_htcc_ab01
build_src_filter = ${heltec_htcc_ab01.build_src_filter}
  +<../examples/kiss_modem/>
